import Head from "next/head";
import styled from "styled-components";

// Imports of icons from styled-icons
// Check their official documentation for https://styled-icons.dev/

import { Nextdotjs } from "@styled-icons/simple-icons/Nextdotjs";
import { Styledcomponents } from "@styled-icons/simple-icons/Styledcomponents";
import { Redux } from "@styled-icons/simple-icons/Redux";
import { PackageIcon } from "@styled-icons/feather/PackageIcon";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Nextjs Starter Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderText>Starter Project for Next js</HeaderText>
      <SubHeaderText>Edit the index.js file to get started</SubHeaderText>
      <SubHeaderText>
        Author : John Moon
        <a href="https://github.com/obiofiong">https://github.com/obiofiong</a>
        <div>
          <a href="https://www.linkedin.com/in/john-obiofiong">
            https://www.linkedin.com/in/john-obiofiong
          </a>
        </div>
      </SubHeaderText>
      <div className="libraries">
        <Card>
          <Nextdotjs height={60} width={60} className="icon" />
          <Text>Next js</Text>
        </Card>
        <Card>
          <Styledcomponents height={60} width={60} className="icon" />
          <Text>Styled Components</Text>
        </Card>
        <Card>
          <Redux height={60} width={60} className="icon" />
          <Text>Redux Toolkit</Text>
        </Card>
        <Card>
          <PackageIcon height={60} width={60} className="icon" />
          <Text>and more...</Text>
          <SubHeaderText>Read the README file</SubHeaderText>
        </Card>
      </div>
    </Container>
  );
}

const Container = styled.div`
  padding: 60px;
  text-align: center;
  margin: 0;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  a {
    color: #838384;
    margin: 0 5px;
  }

  .libraries {
    margin: 30px 0;
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 50px;

    @media only screen and (max-width: 570px) {
      grid-template-columns: 1fr;
    }
  }
`;
const HeaderText = styled.h1`
  font-size: 25px;
  font-weight: 700;
`;
const SubHeaderText = styled.h2`
  font-size: 16px;
  font-weight: 400;
  color: ${(props) => props.theme.colors.base};
  margin: 10px 0;
`;
const Text = styled.p`
  font-size: 20px;
  font-weight: 400;
  color: ${(props) => props.theme.colors.base};
`;
const Card = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 250px;
  width: 250px;
  cursor: pointer;
  border: 1px solid #8aaffd;
  border-radius: 10px;
  box-shadow: rgba(149, 157, 165, 0.2) 0px 8px 24px;
  gap: 30px;
  &:hover {
    background: #f8f8f8;
    box-shadow: none;
    .icon {
      color: ${(props) => props.theme.colors.primary};
    }
  }
`;
